/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 22 02:03:13 GMT 2018
 */

package spark;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import spark.ExceptionHandlerImpl;
import spark.ExceptionMapper;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExceptionMapper_ESTest extends ExceptionMapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = ExceptionMapper.getInstance();
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.getHandler(class0);
      Class<Exception> class1 = Exception.class;
      ExceptionMapper exceptionMapper1 = ExceptionMapper.getInstance();
      Exception exception0 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper0.getHandler(class1);
      Exception exception1 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper0.getHandler(exception1);
      Exception exception2 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper1.map(class1, (ExceptionHandlerImpl) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ExceptionMapper.getInstance();
      ExceptionMapper.getInstance();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = ExceptionMapper.getInstance();
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.getHandler(class0);
      exceptionMapper0.map(class0, (ExceptionHandlerImpl) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = new ExceptionMapper();
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.getHandler(class0);
      Exception exception0 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper0.getHandler(exception0);
      Class<Exception> class1 = Exception.class;
      exceptionMapper0.getHandler(class1);
      exceptionMapper0.getHandler(class1);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = new ExceptionMapper();
      Exception exception0 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper0.getHandler(exception0);
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.map(class0, (ExceptionHandlerImpl) null);
      Class<Exception> class1 = Exception.class;
      exceptionMapper0.getHandler(class1);
      ExceptionMapper exceptionMapper1 = ExceptionMapper.getInstance();
      exceptionMapper1.getHandler(class0);
      Exception exception1 = mock(Exception.class, new ViolatedAssumptionAnswer());
      exceptionMapper1.getHandler(exception1);
      ExceptionMapper exceptionMapper2 = ExceptionMapper.getInstance();
      Class<Exception> class2 = Exception.class;
      exceptionMapper2.getHandler(class2);
      ExceptionMapper.getInstance();
      exceptionMapper0.map(class2, (ExceptionHandlerImpl) null);
      exceptionMapper0.map(class0, (ExceptionHandlerImpl) null);
      ExceptionMapper exceptionMapper3 = ExceptionMapper.getInstance();
      exceptionMapper3.map(class0, (ExceptionHandlerImpl) null);
      ExceptionHandlerImpl exceptionHandlerImpl0 = exceptionMapper1.getHandler((Exception) null);
      // Undeclared exception!
      try { 
        exceptionMapper0.map(class2, exceptionHandlerImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.ExceptionMapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = ExceptionMapper.getInstance();
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.getHandler(class0);
      Class<Exception> class1 = Exception.class;
      exceptionMapper0.getHandler(class1);
      exceptionMapper0.map(class1, (ExceptionHandlerImpl) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ExceptionMapper exceptionMapper0 = ExceptionMapper.getInstance();
      Class<Exception> class0 = Exception.class;
      exceptionMapper0.getHandler((Class<? extends Exception>) null);
      // Undeclared exception!
      try { 
        ExceptionMapper.getInstance();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("spark.ExceptionMapper", e);
      }
  }
}
